Cats99/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests
end

Cats99/app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :birth_date, :name, :sex, :color, :description, presence: true
  validates :sex, inclusion: { in: %w(M F)}

  has_many :cat_rental_requests, :dependent => :destroy

end

Cats99/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED),
      message: "This is not a valid status" }

  belongs_to :cat

  def overlapping_requests
    cat = Cat.find_by(id: self.cat_id)
    data = cat.cat_rental_requests
    s = self.start_date
    e = self.end_date
    requests = data.select do |datum|
      next if datum.id == self.id
      datum.start_date.between?(s, e) || datum.end_date.between?(s, e) || s.between?(datum.start_date, datum.end_date)
    end
  end

  def overlapping_approved_requests
    overlapping_requests.select {|request| request.status == "APPROVED"}
  end

  def overlapping_pending_requests
    overlapping_requests.select {|request| request.status == "PENDING"}
  end

  def approve!
    requests = overlapping_approved_requests + overlapping_pending_requests

    ActiveRecord::Base.transaction do
      self.update(status: "APPROVED")
      requests.each do |request|
        request.deny!
      end
    end
  end

  def deny!
    self.update(status: "DENIED")
  end

  def pending?
  end

end

Cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

Cats99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @cat_rental_requests = CatRentalRequest.all
  end

  def new
    @cat_rental_request = CatRentalRequest.new
    @cat_ids = []
    Cat.all.each do |cat|
      @cat_ids << cat.id
    end
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental_request.save
      redirect_to cat_rental_request_url(@cat_rental_request)
    else
      # render flash: {error: @cat_rental_request.errors.full_messages}
      # @errors = []
      # @errors << @cat_rental_request.errors.full_messages
    end
  end

  def edit
    @cat_rental_request = CatRentalRequest.find_by_id(params[:id])
  end

  def show
    @cat_rental_request = CatRentalRequest.find_by_id(params[:id])
  end

  def update
    @cat_rental_request = CatRentalRequest.find_by_id(params[:id])
    if @cat_rental_request.update(cat_rental_request_params)
      redirect_to cat_rental_request_url(@cat_rental_request)
    else
      # render flash: {error: @cat.errors.full_messages}
      # @errors = []
      # @errors << @cat.errors.full_messages
    end
  end

  private
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end
end

Cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
    flash[:errors] = ["Error"]
    render :new      # @errors = []
      # @errors << @cat.errors.full_messages
    end
  end

  def edit
    @cat = Cat.find_by_id(params[:id])
  end

  def show
    @cat = Cat.find_by_id(params[:id])
    @requests = @cat.cat_rental_requests.order(:start_date)
  end

  def update
    @cat = Cat.find_by_id(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render flash: {error: @cat.errors.full_messages}
      @errors = []
      @errors << @cat.errors.full_messages
    end
  end



  private
  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :description, :birth_date)
  end
end

Cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats99/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

Cats99/app/helpers/cats_helper.rb
module CatsHelper
end

Cats99/app/views/cat_rental_requests/index.html.erb
<h1>Cat Rental Requests</h1>

<% @cat_rental_requests.each do |cat_rental_request| %>
  <ul>
    <li> <%= cat_rental_request.cat_id %><%= cat_rental_request.status %>
    </li>
  </ul>
<% end %>

Cats99/app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_url %>" method="post">
  <%# if action == :edit %>
    <!-- <input type="hidden" name="_method" value="patch"> -->
  <%# end %>
  <label>
    Cat:
    <select name="cat_rental_request[cat_id]">
      <option value=""></option>
      <% @cat_ids.each do |cat_id| %>
      <option value="<%=cat_id%>" <%= "selected" if @cat_rental_request.cat_id == cat_id %>> <%= cat_id %></option>
      <% end %>
    </select>
  </label>
  <label>
    Start date:
    <input type="date" name="cat_rental_request[start_date]" value="<%= @cat_rental_request.start_date %>">
  </label>
  <label>
    End date:
    <input type="date" name="cat_rental_request[end_date]" value="<%= @cat_rental_request.end_date %>">
  </label>
  <input type="submit" value="Submit your cat request">
</form>

Cats99/app/views/cat_rental_requests/show.html.erb
<table>
  <tr>
    <th> Cat ID </th>
    <th> Start date </th>
    <th> End date </th>
    <th> Status </th>
  </tr>
  <tr>
    <td><%= @cat_rental_request.cat_id %></td>
    <td><%= @cat_rental_request.start_date %></td>
    <td><%= @cat_rental_request.end_date %></td>
    <td><%= @cat_rental_request.status %></td>
  </tr>
</table>

Cats99/app/views/cats/_form.html.erb
<% if flash[:errors] %>
  <ul>
  <%= flash[:errors] %> 
  </ul>
<% end %>

<% action_url = (action == :new) ? cats_url : cat_url(cat) %>
<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label>
    Name:
    <input type="text" name="cat[name]" value="<%= @cat.name %>">
  </label>
  <label>
    Sex:
    <input type="radio" name="cat[sex]" value="M" id="cat_sex_male" <%= "checked" if @cat.sex == "M" %>>
    <label for="cat_sex_male">Male</label>
    <input type="radio" name="cat[sex]" value="F" id="cat_sex_female" <%= "checked" if @cat.sex == "F" %>>
    <label for="cat_sex_female">Female</label>
  </label>
  <label>
    Color:
    <select name="cat[color]">
      <option value=""></option>
      <option value="brown" <%= "selected" if @cat.color == "brown" %> >Brown</option>
      <option value="black" <%= "selected" if @cat.color == "black" %> >Black</option>
      <option value="orange" <%= "selected" if @cat.color == "orange" %> >Orange</option>
      <option value="blue" <%= "selected" if @cat.color == "blue" %> >Blue</option>
      <option value="white" <%= "selected" if @cat.color == "white" %> >White</option>
    </select>
  </label>
  <label>
    Birthday:
    <input type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  </label>
  <label>
    Description:
    <textarea name="cat[description]" rows=30 cols=30>
      <%= @cat.description %>
    </textarea>
  </label>
  <input type="submit" value="Submit your cat">
</form>

Cats99/app/views/cats/edit.html.erb
<h2> Edit your cat! </h2>
<%= render "form", cat: @cat, action: :edit %>

Cats99/app/views/cats/index.html.erb
<h1>Cats</h1>

<% @cats.each do |cat| %>
  <ul>
    <li> <%= cat.name %>
    </li>
  </ul>
<% end %>

Cats99/app/views/cats/new.html.erb
<h2> Your new cat! </h2>
<%= render "form", cat: @cat, action: :new %>

Cats99/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<table>
  <tr>
    <th> Sex </th>
    <th> Color </th>
    <th> Birthday </th>
    <th> Description </th>
    <th> Rental Requests </th>

  </tr>
  <tr>
    <td><%= @cat.sex %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.description %></td>
    <td><% @requests.each do |request| %>
          <%= request.start_date  %>
          <%= request.end_date %>
          <%= button_to "Approve", cat_url(@cat), method: :patch, request: :approve!%>
          <%= button_to "Deny", cat_url(@cat), method: :patch, request: :deny!%>
        <% end %>
    </td>
  </tr>
</table>

Cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <!-- <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %> -->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>